## Numpy Random Module
- rand : Random Values in a given shape
- randn : Return a sample (or samples) from the "standard normal" distribution
- randint : Return random integers from low (inclusive) to high (exclusive)
- random : Return random floats in the half-open interval [0.0, 1.0]
- choice : Generates a random sample from a given 1-D array
- Shuffle : Shuffles the contents of a sequence

In [1]:
# Arange Method
import numpy as np
a = np.arange(10) + 5
print(a)

[ 5  6  7  8  9 10 11 12 13 14]


In [2]:
np.random.shuffle(a)  # everytime we run this we get a different output
print(a)

[10 14 11  6  7 12  5  9 13  8]


In [3]:
# printing a random array
a = np.random.rand(2,3)
print(a)

[[0.45575375 0.68309121 0.6298359 ]
 [0.2297297  0.77597355 0.22684927]]


In [10]:
# This returns values from a Standard Normal Distribution
a = np.random.randn(2,3)
print(a)

# It gives 3 numbers btw 5 and 10
a = np.random.randint(5,10,3)
print(a)

# Randomly pick one element from an array
element = np.random.choice([1,4,3,2,11,27])
print(element)

[[-0.3290856   0.14240151 -0.43625553]
 [-1.21495583 -0.62398519 -0.58856564]]
[6 7 8]
3
