## Working with Numpy - used for mathematical operations

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])
print(a)
print(type(a))

print(a.shape) # shape is a tuple which returns the dimensions of your array

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [3]:
b = np.array([[1],[2],[3],[4],[5]])
print(b)
print(b.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


In [4]:
c = np.array([[1,2,3],[4,5,6]])
print(c)
print(c.shape)
print(c[1][1])

[[1 2 3]
 [4 5 6]]
(2, 3)
5


In [5]:
# Create Zeros, Ones, Custom Array
a = np.zeros((3,3))
print(a)


b = np.ones((2,3))
print(b)

# Array of some constant
c = np.full((3,2),5)
print(c)

# Identity Matrix - Size/Square Matrix
d = np.eye(4)
print(d)

# Random Matrix
randomMatrix = np.random.random((2,3))
print(randomMatrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5]
 [5 5]
 [5 5]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.9893407  0.49526363 0.09695324]
 [0.56782785 0.12145818 0.43848326]]


In [6]:
print(randomMatrix[:,1]) # getting an element from the matrix

[0.49526363 0.12145818]


In [7]:
# Updating the elements from the matrix
randomMatrix[1,1:3] = 1  #slicing
print(randomMatrix)

[[0.9893407  0.49526363 0.09695324]
 [0.56782785 1.         1.        ]]


In [8]:
# Set some rows and coloumns with any values
z = np.zeros((3,3), dtype = np.int64) #changing the datatype from float to int
print(z)
z[1,:] = 5
z[:,-1] = 7
print(z)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 7]
 [5 5 7]
 [0 0 7]]


In [9]:
# Datatypes
print(z.dtype)

int64


In [10]:
# Mathematical Operations
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

#element wise addition
print(x+y)
# or we can write as
print(np.add(x,y))

#subtraction
print(x-y)
# or
print(np.subtract(x,y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [11]:
# Multiplication
print(x*y)
# or
print(np.multiply(x,y))

# Division
print(x/y)
# or
print(np.divide(x,y))

# Squareroot
print(np.sqrt(x))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [12]:
# Matrix Multiplication / Dot product
print(x)
print(y)

print(x.dot(y))
print(np.dot(x,y))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [13]:
# Multiplication (Dot Product) of Vectors => Scalar
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
print(a.dot(b))

30


In [14]:
print(a)

[1 2 3 4]


In [15]:
print(sum(a)) #sum of elements of an array

10


In [16]:
print(x)

[[1 2]
 [3 4]]


In [17]:
print(np.sum(x))
print(np.sum(x,axis = 0)) # it is the sum along the coloumns

10
[4 6]


In [18]:
print(np.sum(x))
print(np.sum(x,axis = 1))

10
[3 7]


In [19]:
# Stacking of Arrays
print(a)
b = b**2
print(b)

[1 2 3 4]
[ 1  4  9 16]


In [20]:
np.stack((a,b), axis = 1)

array([[ 1,  1],
       [ 2,  4],
       [ 3,  9],
       [ 4, 16]])

In [21]:
a = np.stack((a,b), axis = 0)

In [22]:
# Reshape a numpy array
a = a.reshape((4,2))
print(a)

[[ 1  2]
 [ 3  4]
 [ 1  4]
 [ 9 16]]
