## Numpy Functions - Statistics
- min, max
- mean
- median
- average
- variance
- standard deviation

In [6]:
import numpy as np
a = np.array([[1,2,3,4],[7,6,2,0]])
print(a)
print(np.min(a))
# Specify axis for the dirrection in case of multidimensional array.
print(np.min(a, axis = 0))
print(np.min(a, axis = 1))

[[1 2 3 4]
 [7 6 2 0]]
0
[1 2 2 0]
[1 0]


In [10]:
# Mean, average all the elements
b = np.array([1,2,3,4,5])
m = sum(b)/5
print(m)
# or you can write as
print(np.mean(b))
print(np.mean(a, axis = 0))
print(np.mean(a, axis = 1))

3.0
3.0
[4.  4.  2.5 2. ]
[2.5  3.75]


In [13]:
c = np.array([1,5,4,2,0])
print(np.median(c))

# Mean vs average is weighted
print(np.mean(c))

# Weights
w = np.array([1,2,3,4,5])
print(np.average(c, weights = w))

2.0
2.4
2.066666666666667


In [18]:
# Variance
print(myStd**2)
# or
print(np.var(c))

3.440000000000001
3.4400000000000004
